"use client";

import jsPDF from "jspdf";

type Props = {
  show: boolean;
  monthlyRevenue: string;
  yearlyRevenue: string;
  logo: string;
  banner?: string;
};

export default function DownloadReport({
  show,
  monthlyRevenue,
  yearlyRevenue,
  logo,
  banner,
}: Props) {
  if (!show) return null;

  function downloadPDF() {
    const pdf = new jsPDF();

    // Header
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.setTextColor(220, 38, 38);
    pdf.text("YouTube Revenue Estimate Report", 20, 20);

    pdf.setDrawColor(220, 38, 38);
    pdf.line(20, 25, 190, 25);

    // Date
    pdf.setFontSize(11);
    pdf.setTextColor(120);
    pdf.text(
      `Generated: ${new Date().toLocaleString()}`,
      20,
      35
    );

    // Revenue Section
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.setTextColor(0);
    pdf.text("Estimated Revenue", 20, 55);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(13);

    pdf.text(`Monthly Revenue : ${monthlyRevenue}`, 20, 75);
    pdf.text(`Yearly Revenue : ${yearlyRevenue}`, 20, 90);

    // Disclaimer
    pdf.setFontSize(10);
    pdf.setTextColor(120);

    pdf.text(
      "Revenue is estimated using a default RPM range of $1-$5.",
      20,
      120
    );

    pdf.text(
      "Actual earnings depend on CPM, audience and engagement.",
      20,
      128
    );

    // Footer
    pdf.setDrawColor(180);
    pdf.line(20, 270, 190, 270);

    pdf.setFontSize(10);
    pdf.setTextColor(90);

    pdf.text("Generated by Creator Toolkit", 20, 278);

    pdf.text("Developed by @Dayanand Kumar", 20, 284);

    pdf.text("© 2026 Creator Toolkit. All Rights Reserved.", 20, 290);

    pdf.save("Revenue-Estimate.pdf");
  }

  return (
    <div className="mt-8 text-center">
      <button
        onClick={downloadPDF}
        className="rounded-xl bg-red-600 px-8 py-4 font-semibold text-white transition hover:bg-red-700"
      >
        📄 Download PDF Report
      </button>
    </div>
  );
}