import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | Creator Toolkit",
  description:
    "Read the disclaimer for Creator Toolkit regarding YouTube revenue estimates, AI-generated content, and informational use.",
};

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-16">

      <h1 className="text-5xl font-black text-slate-900">
        Disclaimer
      </h1>

      <p className="mt-6 text-slate-600">
        Last Updated: July 2026
      </p>

      <div className="mt-10 space-y-10 text-lg leading-8 text-slate-700">

        <section>
          <h2 className="text-3xl font-bold text-slate-900">
            General Information
          </h2>

          <p className="mt-4">
            Creator Toolkit provides free YouTube tools and educational
            content for informational purposes only. While we strive to
            keep our tools accurate and up to date, we do not guarantee
            that every estimate or result will be accurate.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-slate-900">
            Revenue Estimates
          </h2>

          <p className="mt-4">
            Revenue estimates generated by our calculators are based on
            publicly available information and estimated RPM/CPM values.
            Actual YouTube earnings vary depending on audience, content,
            advertiser demand, and many other factors.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-slate-900">
            AI-Generated Content
          </h2>

          <p className="mt-4">
            AI-generated titles, keywords, tags, and descriptions are
            suggestions only. Users should review and edit them before
            publishing content.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-slate-900">
            Third-Party Services
          </h2>

          <p className="mt-4">
            This website may use third-party services such as the YouTube
            Data API, Google Analytics, Google AdSense, and AI providers.
            Their services are governed by their own policies and terms.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-slate-900">
            Contact
          </h2>

          <p className="mt-4">
            If you have any questions regarding this Disclaimer,
            please contact us through the Contact page.
          </p>
        </section>

      </div>

    </main>
  );
}